name: Deploy
on:
  push:
    branches: [ deploy-test ]
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Package
        run: |
          ./gradlew build -x test


      - name: Build Docker App
        run: |
          docker build . -f Dockerfile.app -t olaph-app:latest
