name: Deploy
on:
  push:
    branches: [ deploy-test ]
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Build Package
        run: |
          ./gradlew build -x test
          docker build . -f Dockerfile.app -t olaph-app:latest


      - name: Push to Heroku
        run: |
          heroku login
          heroku container:login
          docker tag olaph-app:latest registry.heroku.com/olaph-slack-app/web
          heroku container:release web