# This is a basic workflow to help you get started with Actions

name: PullRequests

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:8-jdk
    services:
      mongo:
        image: mongo:4.2.11
        ports:
          - 27017:27017
          # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Unit Test
        run: |
          ./gradlew clean unitTest --info --refresh-dependencies